version: '2.4'

services:
  traefik:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/traefik.toml:/traefik.toml
      - /opt/traefik/acme.json:/acme.json

  whoami:
    image: emilevauge/whoami
    labels:
      traefik.enable: "true"

  sonarr:
    image: linuxserver/sonarr
    ports:
      - "8989:8989"
    volumes:
      - ${CONFIG_DIR:?Need to set CONFIG_DIR}/sonarr:/config
      - ${STORAGE_DIR:?Need to set STORAGE_DIR}/tv:/tv
      - ${STORAGE_DIR}/downloads:/downloads
    labels:
      traefik.enable: "true"

  radarr:
    image: linuxserver/radarr
    ports:
      - "7878:7878"
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${STORAGE_DIR}/movies:/movies
      - ${STORAGE_DIR}/downloads:/downloads
    labels:
      traefik.enable: "true"

  plex:
    image: linuxserver/plex
    network_mode: "host"
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${STORAGE_DIR}/movies:/data/movies
      - ${STORAGE_DIR}/tv:/data/tv
      - ${STORAGE_DIR}/transcode:/transcode
    environment:
      VERSION: latest
    labels:
      traefik.enable: "true"

  nzbget:
    image: linuxserver/nzbget
    ports:
      - "6789:6789"
    volumes:
      - ${CONFIG_DIR}/nzbget:/config
      - ${STORAGE_DIR}/downloads:/downloads
      - ${STORAGE_DIR}/intermediate:/intermediate
    labels:
      traefik.enable: "true"
