debug = true
logLevel = "info"
defaultEntryPoints = ["http", "https"]

[api]
dashboard = true

[docker]
domain = "media.varspool.com"
watch  = true

[retry]

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/ssl/*.media.varspool.com/cert.pem"
      keyFile  = "/etc/traefik/ssl/*.media.varspool.com/key.pem"

[file]

[backends]
  [backends.backend-plex]
    [backends.backend-plex.servers]
      [backends.backend-plex.servers.server0]
        url = "http://192.168.1.200:32400"
        weight = 99
  [backends.backend-home-assistant]
    [backends.backend-home-assistant.servers]
      [backends.backend-home-assistant.servers.server0]
        url = "http://192.168.1.200:8123"
        weight = 99
