debug = true
logLevel = "info"
defaultEntryPoints = ["http", "https"]

[api]
dashboard = true

[docker]
domain = "media.varspool.com"
watch  = true

[retry]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/ssl/*.media.varspool.com/cert.pem"
      keyFile  = "/etc/traefik/ssl/*.media.varspool.com/key.pem"
