debug = true
logLevel = "info"
defaultEntryPoints = ["http", "https"]

[api]
dashboard = true

[docker]
domain = "media.varspool.com"
watch  = true

[retry]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.forwardedHeaders]
      trustedIPs = ["192.168.1.0/24", "114.23.221.217/32"]
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.forwardedHeaders]
      trustedIPs = ["192.168.1.0/24", "114.23.221.217/32"]
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/ssl/*.media.varspool.com/cert.pem"
      keyFile  = "/etc/traefik/ssl/*.media.varspool.com/key.pem"

[file]

[backends]
  [backends.plex]
    [backends.plex.servers]
      [backends.plex.servers.server0]
        url = "http://192.168.1.200:32400"
        weight = 99
  [backends.home]
    [backends.home.servers]
      [backends.home.servers.server0]
        url = "http://192.168.1.200:8123"
        weight = 99

[frontends]
  [frontends.plex]
    backend = "plex"
    passHostHeader = true
    [frontends.plex.routes.docker]
      rule = "Host:plex.media.varspool.com"
  [frontends.home]
    backend = "home"
    passHostHeader = true
    [frontends.home.routes.docker]
      rule = "Host:home.media.varspool.com"
