debug = true
logLevel = "info"
defaultEntryPoints = ["http", "https"]

[api]
dashboard = true

[docker]
domain = "media.varspool.com"
watch = true

[retry]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/ssl/star.media.varspool.com.cert"
      keyFile = "/etc/traefik/ssl/star.media.varspool.com.key"

[acme]
email = "dominic@varspool.com"
storage = "acme.json"
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
entryPoint = "https"
onHostRule = true

[acme.httpChallenge]
entryPoint = "http"
