#[entryPoints]
#  [entryPoints.http]
#  address = ":80"
#    [entryPoints.http.redirect]
#    entryPoint = "https"
#  [entryPoints.https]
#  address = ":443"
#  [entryPoints.https.tls]

debug = true

[docker]
domain = "home.varspool.com"
watch = true

#[acme]
#email = "dominic@varspool.com"
#storage = "acme.json"
#caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
#entryPoint = "https"
