#!/bin/bash

set -euo pipefail
set -x

if ! hash minica > /dev/null 2>&1; then
    go get github.com/jsha/minica
fi

minica --domains '*.media.varspool.com'

chmod u=rwX,go=rX '*.media.varspool.com'
chmod u=rw,go=r '*.media.varspool.com/cert.pem' minica.pem
