#!/bin/bash

set -euo pipefail
set -x

if ! hash minica > /dev/null 2>&1; then
    go get github.com/jsha/minica
fi

minica --domains *.media.varspool.com

chmod ugo+rwX *.media.varspool.com # dir
chmod ufo+rw *.media.varspool.com/cert.pem
chmod ugo+rw minica.pem
